[package]
name = "emote-picker"
version = "0.2.0"
authors = ["Patrick Monaghan <0x5f.manpat@gmail.com>"]
edition = "2018"

[dependencies]
web-view = "0.6.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clipboard = "0.5.0"
dirs = "3.0"
