[package]
name = "fetch-emoji-list"
version = "0.1.0"
authors = ["Patrick Monaghan <0x5f.manpat@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
